#!/bin/bash
# Helper script to document Asana MCP tools after Cursor restart
# Run this after restarting Cursor and checking MCP settings

echo "📋 Asana MCP Tools Documentation Helper"
echo "=" | head -c 60 && echo ""
echo ""
echo "After restarting Cursor:"
echo "1. Go to Cursor Settings → MCP"
echo "2. Find Asana server"
echo "3. List all available tools"
echo ""
echo "Then document them here:"
echo ""
echo "Tool List:"
echo "----------"
echo ""
echo "1. Tool Name:"
echo "   Description:"
echo "   Parameters:"
echo "   Essential? [Yes/No]"
echo ""
echo "2. Tool Name:"
echo "   Description:"
echo "   Parameters:"
echo "   Essential? [Yes/No]"
echo ""
echo "... (continue for all tools)"
echo ""
echo "📊 Summary:"
echo "   Total tools: ___"
echo "   Essential tools: ___"
echo "   Target for minimal: 4-6 tools"
